services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Kricha\DoctrineAuditBundle\Controller\AuditController:
        tags: ['controller.service_arguments']
    Kricha\DoctrineAuditBundle\EventSubscriber\FlushListener:
        arguments: ['@Kricha\DoctrineAuditBundle\AuditManager']
    Kricha\DoctrineAuditBundle\EventSubscriber\SchemaAuditSubscriber:
        arguments: ['@Kricha\DoctrineAuditBundle\AuditManager']
    Kricha\DoctrineAuditBundle\Reader\AuditReader:
        arguments: ['@Kricha\DoctrineAuditBundle\AuditConfiguration', '@Doctrine\ORM\EntityManagerInterface', '%kricha_doctrine_audit.configuration%']

    Kricha\DoctrineAuditBundle\Twig\Extension\EntityAuditExtension:
        tags: ['twig.extension']
    Kricha\DoctrineAuditBundle\User\TokenStorageUsernameCallable:
        calls:
            - [setToken, ['@security.token_storage']]
    Kricha\DoctrineAuditBundle\AuditConfiguration:
        arguments: ["%kricha_doctrine_audit.configuration%"]
        calls:
            - [setUsernameCallable, ['@Kricha\DoctrineAuditBundle\User\TokenStorageUsernameCallable']]
    Kricha\DoctrineAuditBundle\AuditManager:
        arguments: ['@Kricha\DoctrineAuditBundle\AuditConfiguration']
